const Data = [
    {
        id: 1,
        title: "iPhone 9",
        description: "An apple mobile which is nothing like apple",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "https://i.pinimg.com/originals/84/ee/48/84ee48dbb18b783a991c2a22103b5649.jpg",
        images: ["https://www.gizmochina.com/wp-content/uploads/2018/07/iphone-9-case-1.jpg", "image2 link"]
    },
    {
        id: 2,
        title: "iPhone X",
        description: "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        price: 899,
        discountPercentage: 17.94,
        rating: 4.44,
        stock: 34,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 3,
        title: "Samsung Universe 9",
        description: "Samsung's new variant which goes beyond Galaxy to the Universe",
        price: 1249,
        discountPercentage: 15.46,
        rating: 4.09,
        stock: 36,
        brand: "Samsung",
        category: "smartphones",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 4,
        title: "OPPO F19",
        description: "OPPO F19 is officially announced in April 2021.",
        price: 280,
        discountPercentage: 17.91,
        rating: 4.3,
        stock: 123,
        brand: "OPPO",
        category: "smartphones",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 5,
        title: "Huawei P30",
        description: "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
        price: 499,
        discountPercentage: 10.58,
        rating: 4.09,
        stock: 32,
        brand: "Huawei",
        category: "smartphones",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 6,
        title: "MacBook Pro",
        description: "MacBook Pro 2021 with mini-LED display may launch between September, November",
        price: 1749,
        discountPercentage: 11.02,
        rating: 4.57,
        stock: 83,
        brand: "Apple",
        category: "laptops",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 7,
        title: "Samsung Galaxy Book",
        description: "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
        price: 1499,
        discountPercentage: 4.15,
        rating: 4.25,
        stock: 50,
        brand: "Samsung",
        category: "laptops",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 8,
        title: "Microsoft Surface Laptop 4",
        description: "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
        price: 1499,
        discountPercentage: 10.23,
        rating: 4.43,
        stock: 68,
        brand: "Microsoft",
        category: "laptops",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 9,
        title: "Infinix INBOOK",
        description: "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Inch FHD Laptop Win10 Grey – 1 Year Warranty",
        price: 1099,
        discountPercentage: 11.83,
        rating: 4.54,
        stock: 96,
        brand: "Infinix",
        category: "laptops",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 10,
        title: "HP Pavilion 15-DK1056WM",
        description: "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
        price: 1099,
        discountPercentage: 6.18,
        rating: 4.43,
        stock: 89,
        brand: "HP",
        category: "laptops",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 11,
        title: "perfume Oil",
        description: "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
        price: 13,
        discountPercentage: 8.4,
        rating: 4.26,
        stock: 65,
        brand: "Impression of Acqua Di Gio",
        category: "fragrances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 12,
        title: "Brown Perfume",
        description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
        price: 40,
        discountPercentage: 15.66,
        rating: 4,
        stock: 52,
        brand: "Royal_Mirage",
        category: "fragrances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 13,
        title: "Fog Scent Xpressio Perfume",
        description: "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
        price: 13,
        discountPercentage: 8.14,
        rating: 4.59,
        stock: 61,
        brand: "Fog Scent Xpressio",
        category: "fragrances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 14,
        title: "Non-Alcoholic Concentrated Perfume Oil",
        description: "Original Al Munakh® Non-Alcoholic Concentrated Perfume Oil Attar 6ml Imported From UAE",
        price: 120,
        discountPercentage: 15.6,
        rating: 4.21,
        stock: 114,
        brand: "Al Munakh",
        category: "fragrances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 15,
        title: "Eau De Perfume Spray",
        description: "Genuine Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
        price: 30,
        discountPercentage: 10.99,
        rating: 4.7,
        stock: 105,
        brand: "Al Rehab",
        category: "fragrances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 16,
        title: "Hyaluronic Acid Serum",
        description: "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
        price: 19,
        discountPercentage: 13.31,
        rating: 4.83,
        stock: 110,
        brand: "L'Oreal Paris",
        category: "skincare",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 17,
        title: "Tree Oil 30ml",
        description: "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
        price: 12,
        discountPercentage: 4.09,
        rating: 4.52,
        stock: 78,
        brand: "Hemani Tea",
        category: "skincare",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 18,
        title: "Oil Free Moisturizer 100ml",
        description: "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
        price: 40,
        discountPercentage: 13.1,
        rating: 4.56,
        stock: 88,
        brand: "Dermive",
        category: "skincare",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 19,
        title: "Skin Beauty Serum.",
        description: "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
        price: 46,
        discountPercentage: 10.68,
        rating: 4.42,
        stock: 54,
        brand: "ROREC White Rice",
        category: "skincare",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 20,
        title: "Freckle Treatment Cream- 15gm",
        description: "Fair & Clear is Pakistan's only pure Freckle cream. Which helps fade freckles, dark spots, and sun spots.",
        price: 70,
        discountPercentage: 16.99,
        rating: 4.06,
        stock: 140,
        brand: "Fair & Clear",
        category: "skincare",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 21,
        title: "- Daal Masoor 500 grams",
        description: "Fine quality Branded Product Keep in a cool and dry place",
        price: 20,
        discountPercentage: 4.81,
        rating: 4.44,
        stock: 133,
        brand: "Saaf & Khaas",
        category: "groceries",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 22,
        title: "Elbow Macaroni - 400 gm",
        description: "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
        price: 14,
        discountPercentage: 15.58,
        rating: 4.57,
        stock: 146,
        brand: "Bake Parlor Big",
        category: "groceries",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 23,
        title: "Orange Essence Food Flavou",
        description: "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
        price: 14,
        discountPercentage: 8.04,
        rating: 4.85,
        stock: 26,
        brand: "Baking Food Items",
        category: "groceries",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 24,
        title: "cereals muesli fruit nuts",
        description: "original fauji cereal muesli fruit nuts",
        price: 46,
        discountPercentage: 16.8,
        rating: 4.94,
        stock: 113,
        brand: "fauji",
        category: "groceries",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 25,
        title: "Gulab Powder 50 Gram",
        description: "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
        price: 70,
        discountPercentage: 13.58,
        rating: 4.87,
        stock: 47,
        brand: "Dry Rose",
        category: "groceries",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 26,
        title: "Plant Hanger For Home",
        description: "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
        price: 41,
        discountPercentage: 17.86,
        rating: 4.08,
        stock: 131,
        brand: "Boho Decor",
        category: "home-decoration",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 27,
        title: "Flying Wooden Bird",
        description: "Package Include 6 Birds with 6 Bell Strings Giving a nice Sound when the wind blows",
        price: 51,
        discountPercentage: 15.58,
        rating: 4.41,
        stock: 17,
        brand: "Flying Wooden",
        category: "home-decoration",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 28,
        title: "3D Embellishment Art Lamp",
        description: "3D led lamp sticker Wall sticker 3d wall art light on/off button cell operated (included)",
        price: 20,
        discountPercentage: 16.49,
        rating: 4.82,
        stock: 54,
        brand: "LED Lights",
        category: "home-decoration",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 29,
        title: "Handcraft Chinese style",
        description: "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
        price: 60,
        discountPercentage: 15.34,
        rating: 4.44,
        stock: 7,
        brand: "luxury palace",
        category: "home-decoration",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 30,
        title: "Key Holder",
        description: "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
        price: 30,
        discountPercentage: 2.92,
        rating: 4.92,
        stock: 54,
        brand: "Golden",
        category: "home-decoration",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 31,
        title: "Mornadi Velvet Bed",
        description: "Mornadi Velvet Bed Base with Headboard Slats Support Classic Style Bedroom Furniture Bed Set",
        price: 40,
        discountPercentage: 16.0,
        rating: 4.0,
        stock: 140,
        brand: "Mornadi",
        category: "furniture",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 32,
        title: "Sofa for Coffe Cafe",
        description: "Ratttan Outdoor furniture Set Waterproof  Rattan Sofa for Coffe Cafe",
        price: 50,
        discountPercentage: 15.59,
        rating: 4.74,
        stock: 30,
        brand: "Ratttan",
        category: "furniture",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 33,
        title: "3 Tier Corner Shelves",
        description: "3 Tier Corner Shelves | 3 PCs Wall Mount Kitchen Shelf | Floating Bedroom Shelf",
        price: 700,
        discountPercentage: 17.11,
        rating: 4.31,
        stock: 106,
        brand: "Kitchen Shelf",
        category: "furniture",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 34,
        title: "Plastic Table",
        description: "V\ICTOR Plastic Table for 6 Persons - Stylish & Sturdy table",
        price: 50,
        discountPercentage: 14.53,
        rating: 4.01,
        stock: 136,
        brand: "V\ICTOR",
        category: "furniture",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 35,
        title: "3 DOOR PORTABLE",
        description: "3 DOOR PORTABLE ACACIA WOODEN ARMARIS",
        price: 41,
        discountPercentage: 17.58,
        rating: 4.06,
        stock: 68,
        brand: "ACACIA",
        category: "furniture",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 36,
        title: "Sleeve Shirt Womens",
        description: "Cotton Solid Color Professional Wear Sleeve Shirt Womens Work Blouses Wholesale Clothing Casual Plain Custom Top OEM Customized",
        price: 90,
        discountPercentage: 10.89,
        rating: 4.26,
        stock: 39,
        brand: "Professional Wear",
        category: "tops",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 37,
        title: "ank Tops for Womens/Girls",
        description: "PACK OF 3 CAMISOLES TANK TOPS FOR WOMEN/GIRLS",
        price: 50,
        discountPercentage: 12.05,
        rating: 4.52,
        stock: 107,
        brand: "Camisas",
        category: "tops",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 38,
        title: "sublimation plain kids tank",
        description: "sublimation plain kids tank tops wholesale",
        price: 30,
        discountPercentage: 12.4,
        rating: 4.8,
        stock: 136,
        brand: "Casual Wear",
        category: "tops",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 39,
        title: "Women Sweaters Wool",
        description: "women's sweaters wool cashmere sweater",
        price: 600,
        discountPercentage: 17.2,
        rating: 4.55,
        stock: 55,
        brand: "Wool",
        category: "tops",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 40,
        title: "Women Jacket",
        description: "Women Jacket Women Jacket waterproof Windbreaker Women Jacket",
        price: 120,
        discountPercentage: 11.57,
        rating: 4.49,
        stock: 44,
        brand: "Windbreaker",
        category: "tops",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 41,
        title: "lighting ceiling kitchen",
        description: "Wholesale slim hanging decorative kid room lighting ceiling kitchen chandeliers pendant light modern",
        price: 30,
        discountPercentage: 14.89,
        rating: 4.83,
        stock: 96,
        brand: "lighting",
        category: "lighting",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 42,
        title: "Metal Ceramic Flower",
        description: "Metal Ceramic Flower Chandelier Home Lighting American Vintage Hanging Lighting Pendant Lamp",
        price: 35,
        discountPercentage: 10.94,
        rating: 4.93,
        stock: 146,
        brand: "Ceramic Flower",
        category: "lighting",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 43,
        title: "3 lights lndenpant kitchen",
        description: "3 lights lndenpant kitchen islan chandelier led induction lighting",
        price: 34,
        discountPercentage: 12.89,
        rating: 4.99,
        stock: 44,
        brand: "LED Lights",
        category: "lighting",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 44,
        title: "American Vintage Wood Pendant Light",
        description: "American Vintage Wood Pendant Light Farmhouse Antique Hanging Lamp Lampara Colgante",
        price: 46,
        discountPercentage: 8.84,
        rating: 4.32,
        stock: 138,
        brand: "Vintage",
        category: "lighting",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 45,
        title: "Crystal chandelier maria theresa for 12 light",
        description: "Crystal chandelier maria theresa for 12 light",
        price: 47,
        discountPercentage: 16.2,
        rating: 4.74,
        stock: 133,
        brand: "Crystal",
        category: "lighting",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 46,
        title: "morning glow lighting",
        description: "morning glow lighting ceiling kitchen chandeliers pendant light modern",
        price: 30,
        discountPercentage: 14.89,
        rating: 4.83,
        stock: 96,
        brand: "lighting",
        category: "lighting",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 47,
        title: "cooker 3 lights 68 cm",
        description: "cooker 3 lights 68 cm long - white, blue & black colors",
        price: 48,
        discountPercentage: 10.94,
        rating: 4.93,
        stock: 150,
        brand: "cooker",
        category: "lighting",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 48,
        title: "Table Lamp Base White",
        description: "Wooden Table Lamp Base White for Bedroom Living Room",
        price: 34,
        discountPercentage: 14.89,
        rating: 4.83,
        stock: 120,
        brand: "Wooden",
        category: "lighting",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 49,
        title: "Aluminum SMD LED",
        description: "Aluminum SMD LED Rechargeable Lamp - Portable Lamp",
        price: 45,
        discountPercentage: 15.92,
        rating: 4.89,
        stock: 150,
        brand: "LED",
        category: "lighting",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 50,
        title: "3 lights adjustable lamp",
        description: "3 lights adjustable pendant lamp with vintage design for living room and dining room",
        price: 50,
        discountPercentage: 18.45,
        rating: 4.76,
        stock: 78,
        brand: "Vintage",
        category: "lighting",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 51,
        title: "Embroidery Pakistani Dress",
        description: "Embroidered, Designer Dress. Attractive & Trendy with Sleeves, Chiffon Dupatta and Trouser",
        price: 150,
        discountPercentage: 10.56,
        rating: 4.72,
        stock: 25,
        brand: "Embroidered",
        category: "clothing",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 52,
        title: "Indian Traditional Dress",
        description: "Indian traditional embroidered dress with heavy stone and zari work",
        price: 120,
        discountPercentage: 12.34,
        rating: 4.67,
        stock: 35,
        brand: "Traditional",
        category: "clothing",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 53,
        title: "Winter Long Coat",
        description: "Stylish winter long coat with high-quality fabric and comfortable fit",
        price: 180,
        discountPercentage: 15.6,
        rating: 4.89,
        stock: 45,
        brand: "WinterWear",
        category: "clothing",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 54,
        title: "Stylish Denim Jacket",
        description: "Fashionable denim jacket for casual wear",
        price: 100,
        discountPercentage: 14.0,
        rating: 4.5,
        stock: 65,
        brand: "FashionWear",
        category: "clothing",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 55,
        title: "Leather Motorcycle Jacket",
        description: "Premium leather motorcycle jacket for bikers",
        price: 250,
        discountPercentage: 16.5,
        rating: 4.9,
        stock: 30,
        brand: "LeatherWear",
        category: "clothing",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 56,
        title: "Floral Summer Dress",
        description: "Lightweight floral summer dress with breathable fabric",
        price: 80,
        discountPercentage: 11.5,
        rating: 4.6,
        stock: 70,
        brand: "SummerWear",
        category: "clothing",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 57,
        title: "Elegant Party Gown",
        description: "Elegant party gown with intricate beadwork and flowy design",
        price: 300,
        discountPercentage: 18.2,
        rating: 4.85,
        stock: 20,
        brand: "PartyWear",
        category: "clothing",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 58,
        title: "Casual Polo Shirt",
        description: "Comfortable casual polo shirt for everyday wear",
        price: 40,
        discountPercentage: 9.8,
        rating: 4.4,
        stock: 90,
        brand: "CasualWear",
        category: "clothing",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 59,
        title: "Running Shoes",
        description: "High-performance running shoes with breathable mesh and durable sole",
        price: 120,
        discountPercentage: 14.3,
        rating: 4.75,
        stock: 100,
        brand: "SportWear",
        category: "footwear",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 60,
        title: "Formal Leather Shoes",
        description: "Elegant formal leather shoes perfect for office wear",
        price: 150,
        discountPercentage: 13.6,
        rating: 4.8,
        stock: 60,
        brand: "LeatherWear",
        category: "footwear",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 61,
        title: "Casual Sneakers",
        description: "Stylish casual sneakers for everyday use",
        price: 90,
        discountPercentage: 12.7,
        rating: 4.65,
        stock: 110,
        brand: "CasualWear",
        category: "footwear",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 62,
        title: "Beach Sandals",
        description: "Comfortable beach sandals with anti-slip sole",
        price: 35,
        discountPercentage: 10.5,
        rating: 4.5,
        stock: 150,
        brand: "SummerWear",
        category: "footwear",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 63,
        title: "Winter Boots",
        description: "Warm and stylish winter boots with fur lining",
        price: 180,
        discountPercentage: 16.4,
        rating: 4.7,
        stock: 55,
        brand: "WinterWear",
        category: "footwear",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 64,
        title: "Smartwatch",
        description: "Feature-packed smartwatch with health tracking and notifications",
        price: 200,
        discountPercentage: 17.0,
        rating: 4.9,
        stock: 40,
        brand: "TechWear",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 65,
        title: "Wireless Earbuds",
        description: "High-quality wireless earbuds with noise cancellation",
        price: 100,
        discountPercentage: 15.5,
        rating: 4.8,
        stock: 80,
        brand: "SoundWear",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 66,
        title: "Bluetooth Speaker",
        description: "Portable Bluetooth speaker with powerful bass and long battery life",
        price: 75,
        discountPercentage: 12.0,
        rating: 4.7,
        stock: 70,
        brand: "SoundWear",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 67,
        title: "Gaming Mouse",
        description: "High-precision gaming mouse with customizable buttons",
        price: 60,
        discountPercentage: 10.0,
        rating: 4.6,
        stock: 90,
        brand: "TechWear",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 68,
        title: "4K Action Camera",
        description: "Waterproof 4K action camera with wide-angle lens",
        price: 150,
        discountPercentage: 14.5,
        rating: 4.85,
        stock: 50,
        brand: "CamWear",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 69,
        title: "Fitness Tracker",
        description: "Wearable fitness tracker with heart rate monitor and step counter",
        price: 80,
        discountPercentage: 13.0,
        rating: 4.7,
        stock: 60,
        brand: "HealthWear",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 70,
        title: "LED TV",
        description: "Smart LED TV with 4K resolution and HDR support",
        price: 500,
        discountPercentage: 18.0,
        rating: 4.9,
        stock: 30,
        brand: "VisionTech",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 71,
        title: "Smartphone",
        description: "Latest model smartphone with high-resolution camera and fast processor",
        price: 800,
        discountPercentage: 10.5,
        rating: 4.8,
        stock: 40,
        brand: "PhoneTech",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 72,
        title: "Laptop",
        description: "High-performance laptop with sleek design and long battery life",
        price: 1000,
        discountPercentage: 12.0,
        rating: 4.9,
        stock: 35,
        brand: "CompTech",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 73,
        title: "Tablet",
        description: "Lightweight tablet with large screen and powerful features",
        price: 400,
        discountPercentage: 14.0,
        rating: 4.7,
        stock: 60,
        brand: "TabTech",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 74,
        title: "Headphones",
        description: "Over-ear headphones with noise-cancelling technology",
        price: 120,
        discountPercentage: 11.5,
        rating: 4.6,
        stock: 70,
        brand: "SoundTech",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 75,
        title: "Smart Home Speaker",
        description: "Voice-controlled smart home speaker with high-quality sound",
        price: 150,
        discountPercentage: 13.0,
        rating: 4.75,
        stock: 50,
        brand: "HomeTech",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 76,
        title: "Digital Camera",
        description: "High-resolution digital camera with multiple lenses",
        price: 700,
        discountPercentage: 15.0,
        rating: 4.85,
        stock: 30,
        brand: "CamTech",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 77,
        title: "Wireless Charger",
        description: "Fast wireless charger compatible with multiple devices",
        price: 50,
        discountPercentage: 9.5,
        rating: 4.65,
        stock: 90,
        brand: "ChargeTech",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 78,
        title: "Smart Thermostat",
        description: "Energy-saving smart thermostat with remote control",
        price: 200,
        discountPercentage: 12.5,
        rating: 4.8,
        stock: 40,
        brand: "HomeTech",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 79,
        title: "4K Monitor",
        description: "Ultra HD 4K monitor with vibrant colors and sharp details",
        price: 350,
        discountPercentage: 10.0,
        rating: 4.7,
        stock: 45,
        brand: "ScreenTech",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 80,
        title: "Gaming Console",
        description: "Latest generation gaming console with immersive graphics",
        price: 500,
        discountPercentage: 14.0,
        rating: 4.9,
        stock: 25,
        brand: "GameTech",
        category: "electronics",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 81,
        title: "Kitchen Blender",
        description: "High-speed kitchen blender with multiple settings",
        price: 100,
        discountPercentage: 11.0,
        rating: 4.6,
        stock: 50,
        brand: "KitchenPro",
        category: "home appliances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 82,
        title: "Air Fryer",
        description: "Healthy cooking air fryer with rapid air technology",
        price: 120,
        discountPercentage: 12.5,
        rating: 4.75,
        stock: 40,
        brand: "KitchenPro",
        category: "home appliances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 83,
        title: "Robot Vacuum Cleaner",
        description: "Automated robot vacuum cleaner with smart navigation",
        price: 300,
        discountPercentage: 13.0,
        rating: 4.8,
        stock: 30,
        brand: "CleanTech",
        category: "home appliances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 84,
        title: "Microwave Oven",
        description: "Compact microwave oven with pre-programmed settings",
        price: 150,
        discountPercentage: 10.5,
        rating: 4.65,
        stock: 40,
        brand: "CookTech",
        category: "home appliances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 85,
        title: "Refrigerator",
        description: "Energy-efficient refrigerator with spacious interior",
        price: 800,
        discountPercentage: 14.5,
        rating: 4.75,
        stock: 20,
        brand: "CoolTech",
        category: "home appliances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 86,
        title: "Dishwasher",
        description: "Quiet and efficient dishwasher with multiple cycles",
        price: 600,
        discountPercentage: 13.5,
        rating: 4.7,
        stock: 25,
        brand: "CleanTech",
        category: "home appliances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 87,
        title: "Electric Kettle",
        description: "Fast-boiling electric kettle with auto shut-off",
        price: 50,
        discountPercentage: 11.5,
        rating: 4.6,
        stock: 60,
        brand: "KitchenPro",
        category: "home appliances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 88,
        title: "Washing Machine",
        description: "Front-load washing machine with multiple wash settings",
        price: 700,
        discountPercentage: 15.0,
        rating: 4.8,
        stock: 30,
        brand: "CleanTech",
        category: "home appliances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 89,
        title: "Espresso Machine",
        description: "High-quality espresso machine with milk frother",
        price: 250,
        discountPercentage: 10.0,
        rating: 4.75,
        stock: 35,
        brand: "BrewTech",
        category: "home appliances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 90,
        title: "Stand Mixer",
        description: "Versatile stand mixer with multiple attachments",
        price: 300,
        discountPercentage: 12.0,
        rating: 4.7,
        stock: 40,
        brand: "KitchenPro",
        category: "home appliances",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 91,
        title: "Cordless Drill",
        description: "Powerful cordless drill with multiple speed settings",
        price: 100,
        discountPercentage: 13.5,
        rating: 4.65,
        stock: 50,
        brand: "ToolTech",
        category: "tools",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 92,
        title: "Electric Screwdriver",
        description: "Compact electric screwdriver with rechargeable battery",
        price: 50,
        discountPercentage: 11.0,
        rating: 4.6,
        stock: 70,
        brand: "ToolTech",
        category: "tools",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 93,
        title: "Circular Saw",
        description: "High-powered circular saw with precision cutting",
        price: 150,
        discountPercentage: 14.5,
        rating: 4.75,
        stock: 40,
        brand: "ToolTech",
        category: "tools",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 94,
        title: "Laser Level",
        description: "Accurate laser level for precise measurements",
        price: 80,
        discountPercentage: 12.5,
        rating: 4.7,
        stock: 50,
        brand: "ToolTech",
        category: "tools",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 95,
        title: "Cordless Leaf Blower",
        description: "Lightweight cordless leaf blower with powerful airflow",
        price: 120,
        discountPercentage: 13.0,
        rating: 4.65,
        stock: 45,
        brand: "GardenTech",
        category: "tools",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 96,
        title: "Electric Lawn Mower",
        description: "Quiet and efficient electric lawn mower with adjustable height settings",
        price: 300,
        discountPercentage: 14.0,
        rating: 4.75,
        stock: 30,
        brand: "GardenTech",
        category: "tools",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 97,
        title: "Pressure Washer",
        description: "High-pressure washer for effective cleaning of outdoor surfaces",
        price: 200,
        discountPercentage: 12.0,
        rating: 4.7,
        stock: 40,
        brand: "CleanTech",
        category: "tools",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 98,
        title: "Hedge Trimmer",
        description: "Electric hedge trimmer with dual-action blades",
        price: 100,
        discountPercentage: 11.5,
        rating: 4.6,
        stock: 50,
        brand: "GardenTech",
        category: "tools",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 99,
        title: "Chainsaw",
        description: "Powerful chainsaw with automatic oiling system",
        price: 250,
        discountPercentage: 15.0,
        rating: 4.75,
        stock: 35,
        brand: "ToolTech",
        category: "tools",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    },
    {
        id: 100,
        title: "Electric Generator",
        description: "Portable electric generator with high power output",
        price: 500,
        discountPercentage: 14.0,
        rating: 4.8,
        stock: 20,
        brand: "PowerTech",
        category: "tools",
        thumbnail: "thumbnail link here",
        images: ["image1 link", "image2 link"]
    }
];